### PR TITLE
LPS-145049 Field title overlaps page

### PR DESCRIPTION
**Pull request by JohnnyMach**

### CODE REVIEW

**Comment by alinedoleron** [comment]
Hello, @JMachado98! Please, could you resend this PR to [liferay-immersion](https://github.com/liferay-immersion/liferay-portal/) repo and close this pr?

**Comment by JohnnyMach** [comment]
> Hello, @JMachado98! Please, could you resend this PR to [liferay-immersion](https://github.com/liferay-immersion/liferay-portal/) repo and close this pr?

Hello @alinedoleron! I've already sent it. There's the PR link: https://github.com/liferay-immersion/liferay-portal/pull/17

**Comment by alinedoleron** [comment]
Thanks, @JMachado98!

**Comment by alinedoleron** [comment]
ci:close

**Pull request closed without merging**
